Models/Aluno.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication2.Models
{
    public class Aluno
    {
        [Key]
        public int Id { get; set; }
        
        [Required(ErrorMessage = "O campo {0} é orbrigatório")]
        [StringLength(30, MinimumLength = 2, ErrorMessage = "O campo {0} deve ter entre {2} e {1} caracteres!")]
        public string? Nome { get; set; }

        [Required(ErrorMessage = "O campo {0} é orbrigatório")]
        [DataType(DataType.DateTime, ErrorMessage = "O campo {0} está no formato incorreto")]
        [Display(Name = "Data de Nascimento")] //Display serve para mostrar algo na tela, nesse caso vai mostrar "Data de nascimento" ao invés de "DataNascimento"
        public DateTime DataNascimento { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [StringLength(60, MinimumLength = 2, ErrorMessage = "O campo {0} deve ter entre {2} e {1} caracteres!")]
        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "O campo {0} está em formato inválido!")] //válida o email
        [EmailAddress(ErrorMessage = "O campo {0} está em formata inválido!")] //valida o email
        public string? Email { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [EmailAddress(ErrorMessage = "O campo {0} está em formata inválido!")] //valida o email
        [Display(Name = "Confirme o email")]
        [Compare("Email", ErrorMessage = "Os emails não são iguais!")] //Compara o campo abaixo com o campo especificado
        [NotMapped] //impede que esse campo se torne uma coluna no banco de dados
        public string? EmailConfirmacao { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigatório")]
        [Range(1, 5, ErrorMessage = "O campo {0} deve estar entre {1} e {2}")] //especifica um intervalo válido
        public int Avaliacao { get; set; }
        public bool Ativo { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AlunosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class AlunosController : Controller
    {
        private readonly AppDbContext Db;

        public AlunosController(AppDbContext db)
        {
            Db = db;
        }

        public async Task<IActionResult> Index()
        {
            //return View(await Db.Alunos.ToListAsync());
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Usando o Bind() eu poss especificar quais campos a minha controller vai receber, ao invés de pegar todos que são enviados
        public async Task<IActionResult> Create([Bind("Id,Nome, DataNascimento,Email,EmailConfirmacao,Avaliacao,Ativo")]Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                Db.Alunos.Add(aluno);
                await Db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(aluno);
        }

        public async Task<IActionResult> Details(int id)
        {
            var aluno = await Db.Alunos.FirstOrDefaultAsync(x => x.Id == id);
            return View(aluno);
        }

        public async Task<IActionResult> Edit(int id)
        {
            var aluno = await Db.Alunos.FindAsync(id);
            return View(aluno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //Usando o Bind() eu poss especificar quais campos a minha controller vai receber, ao invés de pegar todos que são enviados
        public async Task<IActionResult> Edit(int id, [Bind("Id, Nome, DataNascimento, Email, Avaliacao, Ativo")] Aluno aluno)
        {
            if(id != aluno.Id)
            {
                return NotFound();
            }
            //assim o campo EmailConfirmacao não será mais considerado para o ModelState.IsValid
            ModelState.Remove("EmailConfirmacao");
            if (ModelState.IsValid)
            {
                Db.Alunos.Update(aluno);
                await Db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ModelsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class ModelsController : Controller
    {
        public IActionResult Index()
        {
            var aluno = new Aluno()
            {
                Nome = "a",
                Email = "teste",
                EmailConfirmacao = "teste.com"
            };
            if (TryValidateModel(aluno))
            {
                return View(aluno);
            }
            var ms = ModelState;

            var erros = ModelState.Select(x => x.Value?.Errors).Where(y => y?.Count > 0).ToList();

            erros.ForEach(r => Console.WriteLine(r?.First().ErrorMessage));
            
            return View("ErrorViewModel");
        }
    }
}

Controllers/TesteController.cs
using Microsoft.AspNetCore.Mvc;
using System.Runtime.CompilerServices;

namespace WebApplication2.Controllers
{
    [Route("minha-conta", Order = 1)]
    [Route("gestao-minha-conta", Order = 0)] // Order = 0 indica que essa rota tem a preferencia, porém as duas funcionam
    public class TesteController : Controller
    {
        [Route("inicio")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("inicio/{id}/param/{id2?}")] //eu posso passar um parametro que não está especificado na rota, só preciso colocar o nome dele na query string
        //também posso passar parametro não especificados na Action, porém eles serão ignorados, mas a tela não quebra.
        public IActionResult Details(int id, string teste, int id2=1)
        {
            return View(id);
        }
    }
}

Controllers/TesteEFController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class TesteEFController : Controller
    {
        public AppDbContext Db { get; set; }

        //assim que eu conecto a minha controller ao dbContext
        public TesteEFController(AppDbContext db)
        {
            Db = db;
        }

        public IActionResult Index()
        {
            var aluno = new Aluno()
            {
                Nome = "thiago",
                Email = "teste",
                EmailConfirmacao = "teste.com",
                DataNascimento = new DateTime(2001, 04, 05),
                Avaliacao = 5,
                Ativo = true
            };
            Db.Alunos.Add(aluno);
            Db.SaveChanges();

            var alunoChange = Db.Alunos.FirstOrDefault(a => a.Nome.Contains("thiago"));
            alunoChange.Nome = "Thiago Santos";
            
            Db.Alunos.Update(alunoChange);
            Db.SaveChanges();

            Db.Alunos.Remove(alunoChange);
            Db.SaveChanges();
            return View();
        }
    }
}

ViewComponents/SaudacaoAlunoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;

namespace WebApplication2.ViewComponents
{
    public class SaudacaoAlunoViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(int idade)
        {
            var aluno = new Aluno() { Nome = "Thiago"};
            return View(aluno);
        }
    }
}

Views/Alunos/Create.cshtml
@model Aluno

<h4>Preencha os dados</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @* retorna os erros das validações da controller *@
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control"/>
                @* span onde será mostrado o erro de validação*@
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailConfirmacao" class="control-label"></label>
                <input asp-for="EmailConfirmacao" class="form-control" />
                <span asp-validation-for="EmailConfirmacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label"></label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Ativo" class="form-check-input" /> @Html.DisplayNameFor(Model => Model.Ativo)
            </div>
            <button class="btn btn-info">Enviar</button>
        </form>
    </div>
</div>

@* o bloco abaixo só é executado após a função RenderBody() no Layout e após as chamadas de arquivos javascripts presentes nele, esse bloco pode ter qualquer nome, não precisa
    ser necessáriamente "Scripts", só precisa ser o mesmo que está lá no RenderSection.
*@
@section Scripts{
    await @Html.RenderPartialAsync("_ValidationScriptsPartial");
}

Views/Alunos/Details.cshtml
@model Aluno

<h4>Preencha os dados</h4>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(Model => Model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(Model => Model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(Model => Model.DataNascimento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(Model => Model.DataNascimento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(Model => Model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(Model => Model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(Model => Model.Avaliacao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(Model => Model.Avaliacao)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(Model => Model.Ativo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(Model => Model.Ativo)
        </dd>
    </dl>
</div>

Views/Alunos/Edit.cshtml
@model Aluno

<h4>Preencha os dados</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @* retorna os erros das validações da controller *@
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                @* span onde será mostrado o erro de validação*@
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label"></label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="Ativo" class="form-check-input" /> @Html.DisplayNameFor(Model => Model.Ativo)
            </div>
            <button class="btn btn-info">Editar</button>
        </form>
    </div>
</div>

@* o bloco abaixo só é executado após a função RenderBody() no Layout e após as chamadas de arquivos javascripts presentes nele, esse bloco pode ter qualquer nome, não precisa
    ser necessáriamente "Scripts", só precisa ser o mesmo que está lá no RenderSection.
*@
@section Scripts {
        await @Html.RenderPartialAsync("_ValidationScriptsPartial");
}

Views/Alunos/Index.cshtml
@model IEnumerable<Aluno>

    <table class="table">
        <thread>
            <tr>
                <th>@Html.DisplayNameFor(Model => Model.Nome)</th>
            </tr>
        <tr>
            <th>@Html.DisplayNameFor(Model => Model.DataNascimento)</th>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(Model => Model.Email)</th>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(Model => Model.Avaliacao)</th>
        </tr>
        <tr>
            <th>@Html.DisplayNameFor(Model => Model.Ativo)</th>
        </tr>
        </thread>
        <tbody>
        @{
            foreach(var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataNascimento)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Avaliacao)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ativo)
                    </td>
                    <td>
                        //asp-route-[nome do parametro da controller]
                        <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                        <a asp-action="Details" asp-route-id="@item.Id">Editar</a>
                    </td>
                </tr>
            }
        }
        </tbody>
    </table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/Components/SaudacaoAluno/Default.cshtml
@model Aluno

<h4>Ola @Model.Nome, seja bem vindo!</h4>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
</head>
<body>
    <!--posso chamar assim-->
    <!--<partial name="_MenuLayout"/>-->

    <!--ou assim, desse modo a rendireização do resto da view não fica esperando essa partial ser renderizada, já que ela renderizada-->
    @await Html.PartialAsync("_MenuLayout")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            @* @await Component.InvokeAsync("SaudacaoAluno") *@
            <vc:saudacao-aluno idade="10"/>
            <!--passando parametro idade-->
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @* o RenderSection serve para renderizar um bloco de javascript da página que está sendo carregada no RenderBody(), é preciso ser utilizado dessa forma pois o javascript
do layout é carregado após a renderização da página, então se o script da página utilizar o jquery por exemplo, não iria funcionar pois a chamado do jquery só ocorre depois, então
o RenderSection permite que a tela seja carregada pelo RenderBody e só após isso irá executar o javascript que está dentro dela
    *@
</body>
</html>

Views/Shared/_MenuLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Models" asp-action="Index">Models</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Create">Cadastrar aluno</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

Views/Teste/Details.cshtml
<div>detalhes</div>

Views/Teste/Index.cshtml
<div>teste</div>